export const appText = {
	knowledgeBase: "База знаний",
	pageNotFound: "Страница не найдена",
	backHome: "Вернуться на главную",
	selectTopic: "Выберите тему",
	findQuestion: "Найти вопрос...",
	dataNotFound: "Данные не найдены",
	contentNotFound: "Запрашиваемый контент не найден",
	goBack: "Вернуться назад",
	addTopic: "Добавить тему",
	addQuestion: "Добавить вопрос",
	error: "Ошибка",
	add: "Добавить",
	edit: "Редактировать",
	delete: "Удалить",
	save: "Сохранить",
	cancel: "Отмена",
	check: "Проверить",
	passed: "Пройдено",
	notPassed: "Не пройдено",
	markAsCompleted: "Отметить как пройденное",
	markAsNotCompleted: "Отметить как не пройденное",
	topicsOfQuestions: "Темы вопросов",
	topicNotFound: "Тема не найдена",
	topicsNotFound: "Темы не найдены",
	backToTopics: "Вернуться к темам",
	backToQuestions: "Вернуться к вопросам",
	topicStatusUpdated: "Статус темы обновлен 📝",
	topicStatusNotUpdated: "Не удалось обновить статус темы",
	questionStatusUpdated: "Статус вопроса обновлен 📝",
	questionStatusNotUpdated: "Не удалось обновить статус вопроса",
	questionNotFound: "Вопрос не найден",
	questionNotFoundAndRefresh:
		"Вопрос не найден. Попробуйте обновить страницу.",
	from: "из",
	topicDeleted: "Тема успешно удалена",
	questionDeleted: "Вопрос успешно удален",
	topicNotDeleted: "Не удалось удалить тему",
	questionNotDeleted: "Не удалось удалить вопрос",
	topicDeleteQuestion: "Удалить тему и все вопросы в ней? 👀",
	questionDeleteQuestion: "Вы хотите удалить вопрос из темы? 👀",
	enterPassword: "Введите пароль",
	incorrectPassword: "Неверный пароль",
	accessToFunctionality: "Доступ к функционалу",
	enterPasswordDescription:
		"Введите пароль для получения доступа для добавления / редактирования / удаления тем и вопросов",
	enterNameTopic: "Введите название темы",
	enterNameQuestion: "Введите название вопроса",
	editTopic: "Редактировать тему",
	editQuestion: "Редактировать вопрос",
	topicName: "Название темы",
	questionName: "Название вопроса",
	questionText: "Текст вопроса",
	questionTitle: "Заголовок вопроса",
	enterQuestionTitle: "Введите заголовок вопроса",
	enterQuestionText: "Введите текст вопроса",
	enterQuestionTopic: "Выберите тему",
	success: "Успешно",
	wasError: "Произошла ошибка",
	accessSuccess: "Доступ получен",
	accessError: "Не удалось получить доступ",
	questionUpdated: "Вопрос обновлен 📝",
	questionAdded: "Вопрос добавлен",
	topicUpdated: "Тема обновлена 📝",
	topicAdded: "Тема добавлена",
	logoutSuccess: "Выход выполнен",
	resetColor: "Сбросить цвет",
	textColor: "Цвет текста"
} as const;
