import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";

import "./globals.css";
import { Header, Providers } from "@/shared/components";

const robotoMono = Roboto_Mono({
	subsets: ["cyrillic"],
	variable: "--font-roboto-mono",
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Knowledge",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={robotoMono.variable}>
				<Providers>
					<Header />
					<main className="flex-1 px-5 py-10 max-w-[1440px] w-full mx-auto max-sm:py-6">
						{children}
					</main>
				</Providers>
			</body>
		</html>
	);
}
